version: '3.8'

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: discord-webhook-n8n-bot:local
    container_name: discord-webhook-n8n-bot
    volumes:
      - ./:/app
    working_dir: /app
    command: python main.py